### ISSUE TITLE
在matlab下的训练

### ISSUE THREAD

**Issue by heiitu** [zhanglaplace/Faster_rcnn_Cplusplus_vs2013#1]
请问作者有用过matlab下的训练方式吗，训练出来是否是两个模型文件？

**Comment by zhanglaplace** [comment]
@heiitu  没有，我电脑配置不够用，暂时还没训练。不过过段时间换电脑了，可能也会自己训练模型看看。

**Comment by zhanglaplace** [comment]
@heiitu 昨天我训练了下模型，是两个模型文件
