### ISSUE TITLE
请问遇到过 register.h debug运行时会将namespace caffe 里面的内容重复运行的情况吗

### ISSUE THREAD

**Issue by chenying1204** [zhanglaplace/Faster_rcnn_Cplusplus_vs2013#2]
REGISTER_LAYER_CLASS(Convolution);
REGISTER_LAYER_CLASS(ReLU);
REGISTER_LAYER_CLASS(Pooling);
REGISTER_LAYER_CLASS(LRN);
REGISTER_LAYER_CLASS(Softmax);
第一次运行上面这几个函数可以正常通过，到第二次	REGISTER_LAYER_CLASS(Convolution);
就会在layer_factory.hpp   AddCreator(const string& type, Creator creator) {CHECK_EQ(registry.count(type), 0)}这里出错，这里的registry 的size 是5 。
按理说不应该运行第二次的吧。。。。。是vs2013 哪里配置有问题吗

**Comment by zhanglaplace** [comment]
layer_factory.hpp的第67行，注释CHECK_EQ
static void AddCreator(const string& type, Creator creator) {
    CreatorRegistry& registry = Registry();
    //CHECK_EQ(registry.count(type), 0)
       // << "Layer type " << type << " already registered.";
	if (registry.count(type)==0){
		std::cout <<  "Layer type " << type << " already registered.\n";
	}
    registry[type] = creator;
  }

**Comment by chenying1204** [comment]
原来是这样，非常感谢！
