### ISSUE TITLE
应用到自己的数据集的时候碰到的一些问题

### ISSUE THREAD

**Issue by hetiey** [zhanglaplace/Faster_rcnn_Cplusplus_vs2013#3]
首先非常感谢作者的辛勤付出。
我遇到的问题是，当我采用自己的数据集替换原本的数据集时，得到的结果与matlab下结果不一致，目前仅在Caffe_Net.cpp下修改了类别名及类别数量，由于还未了解清楚到faster rcnn的全貌，未对其他地方进行修改，请问有什么建议吗？

**Comment by zhanglaplace** [comment]
@hetiey 修改了下Caffe_Net预处理的部分，ubuntu上的结果与windows有差异，具体还没验证
